### ISSUE TITLE
How to save the quantized model properly for wav2vec.

### ISSUE THREAD

**Issue by vigneshgig** [georgian-io/Knowledge-Distillation-Toolkit#2]
I want to directly load the quantized model. So how to save the wav2vec model properly.

**Comment by zilunpeng** [comment]
I haven't tried to save and load quantized model. Maybe this thread (https://discuss.pytorch.org/t/how-do-i-save-and-load-quantization-model/64188/4) will help? 

You may also save the original model and quantize it after loading.
