### ISSUE TITLE
Issue installing wav2letter

### ISSUE THREAD

**Issue by sarathsurpur** [georgian-io/Knowledge-Distillation-Toolkit#3]
Hi Georgian, 

Could you please share details on how did you do installation of wav2letter package, I tried following the instructions specified in the original repository, but still facing an issue. 

Thanks in advance!!

**Comment by neemiasbsilva** [comment]
Hi @sarathsurpur, 

Wav2letter moved for flashlight project, so if you want to use wav2letter you have to install flashlight project.
For install in your local environment you can follow the step show in this [README](https://github.com/flashlight/flashlight#building)

But if you want to use Google Colab for quickly try, the author also shared a simple [guide](https://github.com/flashlight/flashlight/blob/main/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb). 

I hope this can be helpful.
