### ISSUE TITLE
how to run wav2vec_quantize?

### ISSUE THREAD

**Issue by mehrdad78** [georgian-io/Knowledge-Distillation-Toolkit#6]
hi there.
i want to quantize a wav2vec model by your script
but i got a lot of error when i want to run it.
how can run it?
i got the error for fairseq_mode and wav2letter

**Comment by neemiasbsilva** [comment]
Hi @mehrdad78 , 

Wav2letter moved for flashlight project, so if you want to use wav2letter you have to install flashlight project.
For install in your local environment you can follow the step show in this [README](https://github.com/flashlight/flashlight#building)

But if you want to use Google Colab for quickly try, the author also shared a simple [guide](https://github.com/flashlight/flashlight/blob/main/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb). 

I hope this can be helpful.
